# Workflow used for generating a set of known workflow run outcomes
# to be tested by github-metrics.
# It is not possible to use Github's API to search by time for workflow
# runs, so, after the github-metrics tests are in place, this run should NEVER be run
# again, as it would throw off the expectations in those tests.
name: Workflow Runs Create Test Data
on:
  workflow_dispatch:
    inputs:
      should_pass:
        description: "Whether the run should pass"
        required: true
        default: true
      sleep_seconds:
        description: "How long to sleep"
        required: false
        default: 5

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep
        if: github.event_name == 'workflow_dispatch'
        run: sleep ${{ github.event.inputs.sleep_seconds }}

      - name: Run
        if: github.event_name == 'workflow_dispatch'
        run: if [ "${{github.event.inputs.should_pass}}" != "true" ]; then exit 1; fi
